# docker-compose.yml
version: '3.4'
services:
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      vscode:
        aliases:
            - vscode
# -- GraphQL App ---
  nodejs:
    container_name: graphqlapp
    build:
      context: ./app
      dockerfile: Dockerfile
    networks:
      vscode:
        aliases:
            - vscode
    ports:
      - '3010:3010'
    environment:
      - REDIS_HOST=redis
      - NODE_ENV=development
      - ENV_NAME=dev
      - PORT=3010
      - API_KEY=38838388383838338
      - RESTRICTED=false
    volumes:
      - ./app/src:/app/src
networks:
  vscode:
    driver: bridge